using System;
using System.Collections.Generic;

using EntityLayer.Interfaces;

namespace EntityLayer.Models
{
    public partial class CartridgeView : IEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CartridgeName { get; set; }
        public int CartridgeLoadId { get; set; }
        public string CartridgeLoadViewName { get; set; }
        public string CartridgeLoadViewCartridgeLoadName { get; set; }
        public int? CartridgeLoadViewCaliberId { get; set; }
        public string CartridgeLoadViewCaliberViewName { get; set; }
        public decimal? CartridgeLoadViewCaliberViewDiameter { get; set; }
        public int? CartridgeLoadViewCaliberViewDiameterUnitId { get; set; }
        public string CartridgeLoadViewCaliberViewDiameterUnitViewName { get; set; }
        public string CartridgeLoadViewCaliberViewDiameterUnitViewPlural { get; set; }
        public string CartridgeLoadViewCaliberViewDiameterUnitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewCaliberViewDiameterUnitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewCaliberViewDiameterUnitViewUnitTypeName { get; set; }
        public string CartridgeLoadViewCaliberViewDiameterUnitViewUnitTypeNotes { get; set; }
        public string CartridgeLoadViewCaliberViewDiameterUnitViewNotes { get; set; }
        public decimal? CartridgeLoadViewCaliberViewBrassLength { get; set; }
        public int? CartridgeLoadViewCaliberViewBrassLengthUnitId { get; set; }
        public string CartridgeLoadViewCaliberViewBrassLengthUnitViewName { get; set; }
        public string CartridgeLoadViewCaliberViewBrassLengthUnitViewPlural { get; set; }
        public string CartridgeLoadViewCaliberViewBrassLengthUnitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewCaliberViewBrassLengthUnitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewCaliberViewBrassLengthUnitViewTypeName { get; set; }
        public string CartridgeLoadViewCaliberViewBrassLengthUnitViewTypeNotes { get; set; }
        public string CartridgeLoadViewCaliberViewBrassLengthUnitViewNotes { get; set; }
        public int? CartridgeLoadViewCaliberViewPrimerTypeId { get; set; }
        public string CartridgeLoadViewCaliberViewPrimerTypeName { get; set; }
        public string CartridgeLoadViewCaliberViewPrimerTypeAbbreviation { get; set; }
        public string CartridgeLoadViewCaliberViewPrimerTypeNotes { get; set; }
        public int? CartridgeLoadViewCaliberViewSortOrder { get; set; }
        public string CartridgeLoadViewCaliberViewNotes { get; set; }
        public int? CartridgeLoadViewBulletId { get; set; }
        public string CartridgeLoadViewBulletViewName { get; set; }
        public string CartridgeLoadViewBulletViewBulletName { get; set; }
        public string CartridgeLoadViewBulletViewBulletFullName { get; set; }
        public int? CartridgeLoadViewBulletViewBulletTypeId { get; set; }
        public string CartridgeLoadViewBulletViewBulletTypeName { get; set; }
        public string CartridgeLoadViewBulletViewBulletTypeAbbreviation { get; set; }
        public string CartridgeLoadViewBulletViewBulletTypeNotes { get; set; }
        public int? CartridgeLoadViewBulletViewMaterialId { get; set; }
        public string CartridgeLoadViewBulletViewMaterialName { get; set; }
        public string CartridgeLoadViewBulletViewMaterialNotes { get; set; }
        public decimal? CartridgeLoadViewBulletViewDiameter { get; set; }
        public int? CartridgeLoadViewBulletViewDiameterUnitId { get; set; }
        public string CartridgeLoadViewBulletViewDiameterUnitViewName { get; set; }
        public string CartridgeLoadViewBulletViewDiameterUnitViewPlural { get; set; }
        public string CartridgeLoadViewBulletViewDiameterUnitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewBulletViewDiameterUnitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewBulletViewDiameterUnitViewUnitTypeName { get; set; }
        public string CartridgeLoadViewBulletViewDiameterUnitViewUnitTypeNotes { get; set; }
        public string CartridgeLoadViewBulletViewDiameterUnitViewNotes { get; set; }
        public int? CartridgeLoadViewBulletViewMass { get; set; }
        public int? CartridgeLoadViewBulletViewMassUnitId { get; set; }
        public string CartridgeLoadViewBulletViewMassUnitViewName { get; set; }
        public string CartridgeLoadViewBulletViewMassUnitViewPlural { get; set; }
        public string CartridgeLoadViewBulletViewMassUnitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewBulletViewMassUnitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewBulletViewMassUnitViewUnitTypeName { get; set; }
        public string CartridgeLoadViewBulletViewMassUnitViewUnitTypeNotes { get; set; }
        public string CartridgeLoadViewBulletViewMassUnitViewNotes { get; set; }
        public decimal? CartridgeLoadViewBulletViewSectionalDensity { get; set; }
        public decimal? CartridgeLoadViewBulletViewBallisticCoefficient { get; set; }
        public decimal? CartridgeLoadViewBulletViewLength { get; set; }
        public int? CartridgeLoadViewBulletViewLengthUnitId { get; set; }
        public string CartridgeLoadViewBulletViewLengthUnitViewName { get; set; }
        public string CartridgeLoadViewBulletViewLengthUnitViewPlural { get; set; }
        public string CartridgeLoadViewBulletViewLengthUnitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewBulletViewLengthUnitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewBulletViewLengthUnitViewUnitTypeName { get; set; }
        public string CartridgeLoadViewBulletViewLengthUnitViewUnitTypeNotes { get; set; }
        public string CartridgeLoadViewBulletViewLengthUnitViewNotes { get; set; }
        public int? CartridgeLoadViewBulletViewManufacturerId { get; set; }
        public string CartridgeLoadViewBulletViewManufacturerName { get; set; }
        public string CartridgeLoadViewBulletViewManufacturerAddress { get; set; }
        public string CartridgeLoadViewBulletViewManufacturerCity { get; set; }
        public string CartridgeLoadViewBulletViewManufacturerState { get; set; }
        public string CartridgeLoadViewBulletViewManufacturerZip { get; set; }
        public string CartridgeLoadViewBulletViewManufacturerUrl { get; set; }
        public string CartridgeLoadViewBulletViewManufacturerNotes { get; set; }
        public string CartridgeLoadViewBulletViewNotes { get; set; }
        public int? CartridgeLoadViewPowderId { get; set; }
        public string CartridgeLoadViewPowderViewName { get; set; }
        public string CartridgeLoadViewPowderViewPowderName { get; set; }
        public int? CartridgeLoadViewPowderViewManufacturerId { get; set; }
        public string CartridgeLoadViewPowderViewManufacturerName { get; set; }
        public string CartridgeLoadViewPowderViewManufacturerAddress { get; set; }
        public string CartridgeLoadViewPowderViewManufacturerCity { get; set; }
        public string CartridgeLoadViewPowderViewManufacturerState { get; set; }
        public string CartridgeLoadViewPowderViewManufacturerZip { get; set; }
        public string CartridgeLoadViewPowderViewManufacturerUrl { get; set; }
        public string CartridgeLoadViewPowderViewManufacturerNotes { get; set; }
        public int? CartridgeLoadViewPowderViewPowderTypeId { get; set; }
        public string CartridgeLoadViewPowderViewPowderTypeName { get; set; }
        public string CartridgeLoadViewPowderViewPowderTypeNotes { get; set; }
        public int? CartridgeLoadViewPowderViewPowderShapeId { get; set; }
        public string CartridgeLoadViewPowderViewPowderShapeName { get; set; }
        public string CartridgeLoadViewPowderViewPowderShapeNotes { get; set; }
        public string CartridgeLoadViewPowderViewNotes { get; set; }
        public decimal? CartridgeLoadViewPowderWeight { get; set; }
        public int? CartridgeLoadViewPowderWeightUnitId { get; set; }
        public string CartridgeLoadViewPowderWeightUnitViewName { get; set; }
        public string CartridgeLoadViewPowderWeightUnitViewPlural { get; set; }
        public string CartridgeLoadViewPowderWeightUnitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewPowderWeightUnitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewPowderWeightUnitViewUnitTypeName { get; set; }
        public string CartridgeLoadViewPowderWeightUnitViewUnitTypeNotes { get; set; }
        public string CartridgeLoadViewPowderWeightUnitViewNotes { get; set; }
        public decimal? CartridgeLoadViewCol { get; set; }
        public int? CartridgeLoadViewColunitId { get; set; }
        public string CartridgeLoadViewColunitViewName { get; set; }
        public string CartridgeLoadViewColunitViewPlural { get; set; }
        public string CartridgeLoadViewColunitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewColunitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewColunitViewUnitTypeName { get; set; }
        public string CartridgeLoadViewColunitViewUnitTypeNotes { get; set; }
        public string CartridgeLoadViewColunitViewNotes { get; set; }
        public int? CartridgeLoadViewVelocity { get; set; }
        public int? CartridgeLoadViewVelocityUnitId { get; set; }
        public string CartridgeLoadViewVelocityUnitViewName { get; set; }
        public string CartridgeLoadViewVelocityUnitViewPlural { get; set; }
        public string CartridgeLoadViewVelocityUnitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewVelocityUnitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewVelocityUnitViewUnitTypeName { get; set; }
        public string CartridgeLoadViewVelocityUnitViewUnitTypeNotes { get; set; }
        public string CartridgeLoadViewVelocityUnitViewNotes { get; set; }
        public int? CartridgeLoadViewPressure { get; set; }
        public int? CartridgeLoadViewPressureUnitId { get; set; }
        public string CartridgeLoadViewPressureUnitViewName { get; set; }
        public string CartridgeLoadViewPressureUnitViewPlural { get; set; }
        public string CartridgeLoadViewPressureUnitViewAbbreviation { get; set; }
        public int? CartridgeLoadViewPressureUnitViewUnitTypeId { get; set; }
        public string CartridgeLoadViewPressureUnitViewUnitTypeName { get; set; }
        public string CartridgeLoadViewPressureUnitViewUnitTypeNotes { get; set; }
        public string CartridgeLoadViewPressureUnitViewNotes { get; set; }
        public string CartridgeLoadViewNotes { get; set; }
        public int BrassId { get; set; }
        public int? BrassViewParentId { get; set; }
        public string BrassViewName { get; set; }
        public string BrassViewBrassName { get; set; }
        public string BrassViewBrassFullName { get; set; }
        public string BrassViewParentBrassFullName { get; set; }
        public int? BrassViewMaterialId { get; set; }
        public string BrassViewMaterialName { get; set; }
        public string BrassViewMaterialNotes { get; set; }
        public int? BrassViewManufacturerId { get; set; }
        public string BrassViewManufacturerName { get; set; }
        public string BrassViewManufacturerAddress { get; set; }
        public string BrassViewManufacturerCity { get; set; }
        public string BrassViewManufacturerState { get; set; }
        public string BrassViewManufacturerZip { get; set; }
        public string BrassViewManufacturerUrl { get; set; }
        public string BrassViewManufacturerNotes { get; set; }
        public int? BrassViewTimesFired { get; set; }
        public string BrassViewNotes { get; set; }
        public int? PrimerId { get; set; }
        public string PrimerViewName { get; set; }
        public string PrimerViewFullName { get; set; }
        public string PrimerViewPrimerName { get; set; }
        public int? PrimerViewPrimerTypeId { get; set; }
        public string PrimerViewPrimerTypeName { get; set; }
        public string PrimerViewPrimerTypeAbbreviation { get; set; }
        public string PrimerViewPrimerTypeNotes { get; set; }
        public int? PrimerViewManufacturerId { get; set; }
        public string PrimerViewManufacturerName { get; set; }
        public string PrimerViewManufacturerAddress { get; set; }
        public string PrimerViewManufacturerCity { get; set; }
        public string PrimerViewManufacturerState { get; set; }
        public string PrimerViewManufacturerZip { get; set; }
        public string PrimerViewManufacturerUrl { get; set; }
        public string PrimerViewManufacturerNotes { get; set; }
        public string PrimerViewNotes { get; set; }
        public int ManufacturerId { get; set; }
        public string ManufacturerName { get; set; }
        public string ManufacturerShortName { get; set; }
        public string ManufacturerAddress { get; set; }
        public string ManufacturerCity { get; set; }
        public string ManufacturerState { get; set; }
        public string ManufacturerZip { get; set; }
        public string ManufacturerUrl { get; set; }
        public string ManufacturerNotes { get; set; }
        public string Notes { get; set; }
    }
}
