using System;
using System.Collections.Generic;

namespace ShootingService.Models
{
    public partial class CartridgeLoadView
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string CartridgeLoadName { get; set; }
        public int CaliberId { get; set; }
        public string CaliberViewName { get; set; }
        public decimal? CaliberViewDiameter { get; set; }
        public int? CaliberViewDiameterUnitId { get; set; }
        public string CaliberViewDiameterUnitViewName { get; set; }
        public string CaliberViewDiameterUnitViewPlural { get; set; }
        public string CaliberViewDiameterUnitViewAbbreviation { get; set; }
        public int? CaliberViewDiameterUnitViewUnitTypeId { get; set; }
        public string CaliberViewDiameterUnitViewUnitTypeName { get; set; }
        public string CaliberViewDiameterUnitViewUnitTypeNotes { get; set; }
        public string CaliberViewDiameterUnitViewNotes { get; set; }
        public decimal? CaliberViewBrassLength { get; set; }
        public int? CaliberViewBrassLengthUnitId { get; set; }
        public string CaliberViewBrassLengthUnitViewName { get; set; }
        public string CaliberViewBrassLengthUnitViewPlural { get; set; }
        public string CaliberViewBrassLengthUnitViewAbbreviation { get; set; }
        public int? CaliberViewBrassLengthUnitViewUnitTypeId { get; set; }
        public string CaliberViewBrassLengthUnitViewTypeName { get; set; }
        public string CaliberViewBrassLengthUnitViewTypeNotes { get; set; }
        public string CaliberViewBrassLengthUnitViewNotes { get; set; }
        public int? CaliberViewPrimerTypeId { get; set; }
        public string CaliberViewPrimerTypeName { get; set; }
        public string CaliberViewPrimerTypeAbbreviation { get; set; }
        public string CaliberViewPrimerTypeNotes { get; set; }
        public int? CaliberViewSortOrder { get; set; }
        public string CaliberViewNotes { get; set; }
        public int BulletId { get; set; }
        public string BulletViewName { get; set; }
        public string BulletViewBulletName { get; set; }
        public string BulletViewBulletFullName { get; set; }
        public int? BulletViewBulletTypeId { get; set; }
        public string BulletViewBulletTypeName { get; set; }
        public string BulletViewBulletTypeAbbreviation { get; set; }
        public string BulletViewBulletTypeNotes { get; set; }
        public int? BulletViewMaterialId { get; set; }
        public string BulletViewMaterialName { get; set; }
        public string BulletViewMaterialNotes { get; set; }
        public decimal? BulletViewDiameter { get; set; }
        public int? BulletViewDiameterUnitId { get; set; }
        public string BulletViewDiameterUnitViewName { get; set; }
        public string BulletViewDiameterUnitViewPlural { get; set; }
        public string BulletViewDiameterUnitViewAbbreviation { get; set; }
        public int? BulletViewDiameterUnitViewUnitTypeId { get; set; }
        public string BulletViewDiameterUnitViewUnitTypeName { get; set; }
        public string BulletViewDiameterUnitViewUnitTypeNotes { get; set; }
        public string BulletViewDiameterUnitViewNotes { get; set; }
        public int? BulletViewMass { get; set; }
        public int? BulletViewMassUnitId { get; set; }
        public string BulletViewMassUnitViewName { get; set; }
        public string BulletViewMassUnitViewPlural { get; set; }
        public string BulletViewMassUnitViewAbbreviation { get; set; }
        public int? BulletViewMassUnitViewUnitTypeId { get; set; }
        public string BulletViewMassUnitViewUnitTypeName { get; set; }
        public string BulletViewMassUnitViewUnitTypeNotes { get; set; }
        public string BulletViewMassUnitViewNotes { get; set; }
        public decimal? BulletViewSectionalDensity { get; set; }
        public decimal? BulletViewBallisticCoefficient { get; set; }
        public decimal? BulletViewLength { get; set; }
        public int? BulletViewLengthUnitId { get; set; }
        public string BulletViewLengthUnitViewName { get; set; }
        public string BulletViewLengthUnitViewPlural { get; set; }
        public string BulletViewLengthUnitViewAbbreviation { get; set; }
        public int? BulletViewLengthUnitViewUnitTypeId { get; set; }
        public string BulletViewLengthUnitViewUnitTypeName { get; set; }
        public string BulletViewLengthUnitViewUnitTypeNotes { get; set; }
        public string BulletViewLengthUnitViewNotes { get; set; }
        public int? BulletViewManufacturerId { get; set; }
        public string BulletViewManufacturerName { get; set; }
        public string BulletViewManufacturerAddress { get; set; }
        public string BulletViewManufacturerCity { get; set; }
        public string BulletViewManufacturerState { get; set; }
        public string BulletViewManufacturerZip { get; set; }
        public string BulletViewManufacturerUrl { get; set; }
        public string BulletViewManufacturerNotes { get; set; }
        public string BulletViewNotes { get; set; }
        public int? PowderId { get; set; }
        public string PowderViewName { get; set; }
        public string PowderViewPowderName { get; set; }
        public int? PowderViewManufacturerId { get; set; }
        public string PowderViewManufacturerName { get; set; }
        public string PowderViewManufacturerAddress { get; set; }
        public string PowderViewManufacturerCity { get; set; }
        public string PowderViewManufacturerState { get; set; }
        public string PowderViewManufacturerZip { get; set; }
        public string PowderViewManufacturerUrl { get; set; }
        public string PowderViewManufacturerNotes { get; set; }
        public int? PowderViewPowderTypeId { get; set; }
        public string PowderViewPowderTypeName { get; set; }
        public string PowderViewPowderTypeNotes { get; set; }
        public int? PowderViewPowderShapeId { get; set; }
        public string PowderViewPowderShapeName { get; set; }
        public string PowderViewPowderShapeNotes { get; set; }
        public string PowderViewNotes { get; set; }
        public decimal? PowderWeight { get; set; }
        public int? PowderWeightUnitId { get; set; }
        public string PowderWeightUnitViewName { get; set; }
        public string PowderWeightUnitViewPlural { get; set; }
        public string PowderWeightUnitViewAbbreviation { get; set; }
        public int? PowderWeightUnitViewUnitTypeId { get; set; }
        public string PowderWeightUnitViewUnitTypeName { get; set; }
        public string PowderWeightUnitViewUnitTypeNotes { get; set; }
        public string PowderWeightUnitViewNotes { get; set; }
        public decimal Col { get; set; }
        public int ColunitId { get; set; }
        public string ColunitViewName { get; set; }
        public string ColunitViewPlural { get; set; }
        public string ColunitViewAbbreviation { get; set; }
        public int? ColunitViewUnitTypeId { get; set; }
        public string ColunitViewUnitTypeName { get; set; }
        public string ColunitViewUnitTypeNotes { get; set; }
        public string ColunitViewNotes { get; set; }
        public int? Velocity { get; set; }
        public int? VelocityUnitId { get; set; }
        public string VelocityUnitViewName { get; set; }
        public string VelocityUnitViewPlural { get; set; }
        public string VelocityUnitViewAbbreviation { get; set; }
        public int? VelocityUnitViewUnitTypeId { get; set; }
        public string VelocityUnitViewUnitTypeName { get; set; }
        public string VelocityUnitViewUnitTypeNotes { get; set; }
        public string VelocityUnitViewNotes { get; set; }
        public int? Pressure { get; set; }
        public int? PressureUnitId { get; set; }
        public string PressureUnitViewName { get; set; }
        public string PressureUnitViewPlural { get; set; }
        public string PressureUnitViewAbbreviation { get; set; }
        public int? PressureUnitViewUnitTypeId { get; set; }
        public string PressureUnitViewUnitTypeName { get; set; }
        public string PressureUnitViewUnitTypeNotes { get; set; }
        public string PressureUnitViewNotes { get; set; }
        public string Notes { get; set; }
    }
}
